### ISSUE TITLE
publish gh-page to show demo index.html

### ISSUE THREAD

**Issue by agauniyal** [agauniyal/wireframe#12]

**Comment by wesharehoodies** [comment]
Hi, how can I help?

**Comment by agauniyal** [comment]
@wesharehoodies  I was thinking of hosting a demo for wireframe on github pages. This can now be done either through a gh-pages branch or master branch's /docs folder, which seems more apt to me. You can decide the way you want to proceed and help out with creating a nice demo for styles present in wireframe 😄 . Design it in any way you like, it should help out newcomers to get started.

You can take a look at current index.html to see how wireframe is used. Development is done in develop branch so make sure to open PR against the same. Feel free to ask for any kind of help :)

**Comment by johngarcia9110** [comment]
Is this still up for grabs?

**Comment by ryuhhnn** [comment]
@johngarcia9110 yes sir! Have at it.

**Comment by jsrj** [comment]
Are you still in need of help with this?

**Comment by agauniyal** [comment]
@jsrj sorry but this project will be soon going through a complete rewrite, so this issue should've been closed by me 😅 . Thanks for your interest though :)
