### ISSUE TITLE
Fix Gulp Tasks

### ISSUE THREAD

**Issue by ryuhhnn** [agauniyal/wireframe#18]
Last pull request on "develop" branch broke the default Gulp task by moving sass processing to Express. Fix this to ensure that people not using Express can still compile sass accordingly.

**Comment by frankinedinburgh** [comment]
Hi Ryuhnn. I created a pull request to fix the gulp tasks back to the way they were previously.
https://github.com/agauniyal/wireframe/pull/20

**Comment by ryuhhnn** [comment]
Thank you for this, @frankinedinburgh!
