### ISSUE TITLE
complete all form elements style

### ISSUE THREAD

**Issue by agauniyal** [agauniyal/wireframe#2]
Currently only `button` and `input[type=text]` is styled. All form related styles reside in `lib/_form.scss`.

**Comment by souravmondal93** [comment]
I would love to work on this issue. If you have, any particular requirements, then you can share those resources. If I am not wrong, I have to work on checkboxes, radio buttons and text areas. Please share your ideas on it.

**Comment by agauniyal** [comment]
There are two soft requirements : 
1. try to make it look same across browsers
2. try not to deviate from using simple unobtrusive colors.

I was trying to make a css wireframe framework(modern browsers only) that requires minimum html/css input from user to get a wireframe model ready. You get the original idea, however you're free to take the project in any direction you want.
