### ISSUE TITLE
Add list styles

### ISSUE THREAD

**Issue by ryuhhnn** [agauniyal/wireframe#9]
Unordered and ordered lists

**Comment by ryuhhnn** [comment]
Default styles for <ul> seem to fit pretty fine with the project. Will update index.html to include a list but close this issue for now.

**Comment by agauniyal** [comment]
We just need to update the screenshot in readme, then we could merge changes in master I guess. almost everything's done right now, if there's something you'd like to propose, you're free to create a new issue for that :+1:
